id: PC64B606A
initial_creation_type: ocr
source_metadata:
  volumes:
    8aef050f69b541a58b72929ac48bfcfb:
      base_file: v021.txt
      image_group_id: I1PD95866
      title: དཔལ་གསང་བ་འདུས་པའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1477
      volume_number: 21
